name: TEST RESOURCES - FILES
on: push
jobs:
    stage:
      environment: stage
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4

        - name: Cat File
          run: |
            cd ./src/wazuh/wazuh_managers/integrations
            printf "\n\n=============== List files ================\n"
            ls -a
            printf "\n\n=============== custom-opsgenie ================\n"
            cat custom-opsgenie

        - name: Truncate File
          run: |
            cd ./src/wazuh/wazuh_managers/integrations
            truncate -s 0 custom-opsgenie

        - name: After Truncate File
          run: |
            cd ./src/wazuh/wazuh_managers/integrations
            printf "\n\n=============== List files ================\n"
            ls -a
            printf "\n\n=============== custom-opsgenie ================\n"
            cat custom-opsgenie


