name: TEST RESOURCES - FILES
on: push
jobs:
    stage:
      environment: stage
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4

        - name: List Files
          run: ls -a ./src/wazuh/certs/

        - name: copy folders
          run: |
            cp -R ./src/wazuh/certs/_stg/* ./src/wazuh/certs/

        - name: delete folders
          run: |
            rmdir ./src/wazuh/certs/_prd/

        - name: List Files STG
          run: |
            printf "\n\n=============== Folders STG ================\n"
            ls -a ./src/wazuh/certs/_stg/
            printf "\n\n=============== Files STG dashboard_http ================\n"
            ls -a ./src/wazuh/certs/_stg/dashboard_http
            printf "\n\n=============== Files STG indexer_cluster ================\n"
            ls -a ./src/wazuh/certs/_stg/indexer_cluster

        - name: List Files After
          run: |
            printf "\n\n=============== Folders ================\n"
            ls -a ./src/wazuh/certs/
            printf "\n\n=============== Files dashboard_http ================\n"
            ls -a ./src/wazuh/certs/dashboard_http
            printf "\n\n=============== Files indexer_cluster ================\n"
            ls -a ./src/wazuh/certs/indexer_cluster


        # - name: Cat File
        #   run: |
        #     cd ./src/wazuh/wazuh_managers/integrations
        #     printf "\n\n=============== List files ================\n"
        #     ls -a
        #     printf "\n\n=============== custom-opsgenie ================\n"
        #     cat custom-opsgenie

        # - name: Truncate File
        #   run: |
        #     cd ./src/wazuh/wazuh_managers/integrations
        #     truncate -s 0 custom-opsgenie
        #     truncate -s 0 custom-slack

        # - name: After Truncate File
        #   run: |
        #     cd ./src/wazuh/wazuh_managers/integrations
        #     printf "\n\n=============== List files ================\n"
        #     ls -a
        #     printf "\n\n=============== custom-opsgenie ================\n"
        #     cat custom-opsgenie

        


