name: TEST RESOURCES
on: push
jobs:
    test:
      runs-on: ubuntu-latest
    #   defaults:
    #     run:
    #       working-directory: src
      steps:
        - name: Get code
          uses: actions/checkout@v4
          with:
            path: src

        - name: List Files After
          run: ls -a

        - name: Cat test path
          run: cat main.jsx


    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v4
          with:
            path: src

        - name: List Files After
          run: ls -a

        - name: Cat test path
          run: |
            cd src
            cat main.jsx
